const puzzles = [
	{
		word: "abstaining",
		subword1: "ab",
		subword2: "staining",
		clue: "When you refuse to participate in applying fake tanner to your stomach?",
		structure: 1,
		answer: "abstaining ab staining",
	},
	{
		word: "flagrant",
		subword1: "flag",
		subword2: "rant",
		clue: "Screed about old glory that goes too far?",
		structure: 1,
		answer: "flagrant flag rant",
	},
	{
		word: "mustache",
		subword1: "must",
		subword2: "ache",
		clue: "That handlebar has gotta hurt!",
		structure: 1,
		answer: "mustache must ache",
	},
	{
		word: "briefest",
		subword1: "brie",
		subword2: "fest",
		clue: "French cheese tasting that lasts only a minute?",
		structure: 1,
		answer: "briefest brie fest",
	},
	{
		word: "fanfare",
		subword1: "fan",
		subword2: "fare",
		clue: "The celebratory music heard when purchasing a ticket?",
		structure: 2,
		answer: "fan fare fanfare",
	},
	{
		word: "abacination",
		subWord1: "abaci",
		subWord2: "nation",
		clue: "When a country of people who love old school counting devices blind you for your crimes?",
		structure: 2,
		answer: " abaci nation abacination",
	},
	{
		word: "accountants",
		subword1: "account",
		subword2: "ants",
		clue: "Bean counters recalling insects that attacked after stepping on their colony?",
		structure: 1,
		answer: "accountants account ants",
	},
	// { word: "", subword1: "", subword2: "", clue: "",	answer: ""},
	{
		word: "carpet",
		subword1: "car",
		subword2: "pet",
		clue: "Your vehicle's beloved furry companion that you wipe your feet on?",
		structure: 2,
		answer: "car pet carpet",
	},
	{
		word: "mandate",
		subword1: "man",
		subword2: "date",
		clue: "A gentleman's romantic outing that the government says he has to go on?",
		structure: 2,
		answer: "man date mandate",
	},
	{
		word: "luncheon",
		subword1: "lunch",
		subword2: "eon",
		clue: "A formal midday meal that felt like it lasted forever?",
		structure: 2,
		answer: "lunch eon luncheon",
	},
	{
		word: "canteen",
		subword1: "can",
		subword2: "teen",
		clue: "A 14-year-old tin that keeps soldiers hydrated in the field?",
		structure: 2,
		answer: "can teen canteen",
	},
	{
		word: "rampage",
		subword1: "ramp",
		subword2: "age",
		clue: "When an elderly inclined surface completely loses it?",
		structure: 2,
		answer: "ramp age rampage",
	},
	{
		word: "wardrobe",
		subword1: "ward",
		subword2: "robe",
		clue: "The hospital wing where they store all the gowns?",
		structure: 2,
		answer: "ward robe wardrobe",
	},
	{
		word: "scarecrow",
		subword1: "scare",
		subword2: "crow",
		clue: "A terrified black bird standing guard over the cornfield?",
		structure: 2,
		answer: "scare crow scarecrow",
	},
	{
		word: "hamstring",
		subword1: "ham",
		subword2: "string",
		clue: "A piece of pork on a rope that sidelines athletes?",
		structure: 2,
		answer: "ham string hamstring",
	},
	{
		word: "passport",
		subword1: "pass",
		subword2: "port",
		clue: "The document you need to successfully get through any harbor?",
		structure: 2,
		answer: "pass port passport",
	},
	{
		word: "sunflower",
		subword1: "sun",
		subword2: "flower",
		clue: "A blooming star that literally follows you around the yard?",
		structure: 2,
		answer: "sun flower sunflower",
	},
];

// const potentials = [
// 	{ word: "adopts", subword1: "ad", subword2: "opts", clue: "", answer: "" },
// 	{ word: "", subword1: "", subword2: "", clue: "" }
// ];

module.exports = puzzles;
